import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import PropertyGrid from '../components/Grid'
import Contact from '../components/Contact'
export default function Home() {
  return (
      <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <PropertyGrid />
      <Contact />
    </div>
  )
}
