import Navbar from "../../components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import useSWR from "swr";
import {
  Container,
  Grid,
  GridItem,
  Text,
  Image,
  AspectRatio,
} from "@chakra-ui/react";

const fetcher = async (url) => {
  const res = await fetch(url);
  const data = await res.json();

  if (res.status !== 200) {
    throw new Error(data.message);
  }
  return data;
};

export default function Person() {
  const { query } = useRouter();
  const { data, error } = useSWR(
    () => query.id && `/api/properties/${query.id}`,
    fetcher
  );

  if (error) return <div>{error.message}</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <div>
      <Head>
        <title>{data.propertyName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxW="container.xl">
        {data.thumbnail ? <img src={data.thumbnail} /> : <div>No Image</div>}
        <Grid
          templateColumns={{ base: "repeat(1, 1fr)", md: "repeat(4, 1fr)" }}
          gap={5}
          py="2em"
        >
          {data.image.map((image) => (
            <AspectRatio>
              <Image src={image} />
            </AspectRatio>
          ))}
        </Grid>

        <Grid
          templateColumns={{ base: "repeat(1, 1fr)", md: "repeat(2, 1fr)" }}
          gap={6}
          py="2em"
        >
          <GridItem>
            <Text fontSize="4xl" fontWeight="bold">
              {data.propertyName}
            </Text>
            <Text color="gray.500" fontWeight="semibold">
              {data.location}
            </Text>
            <Text maxW="500px" my="1em" fontSize="lg">
              {data.description}
            </Text>
          </GridItem>
          <AspectRatio >
            <iframe src={`${data.map}`} width="100%" height="350vw"></iframe>
          </AspectRatio>
        </Grid>
      </Container>
    </div>
  );
}
